from modules.inventory_engine import calculate_stock, calculate_stock_by_bodega
from modules.consumption_engine import calculate_consumption, calculate_projection
from modules.reorder_engine import calculate_reorder, generate_excel_export, get_export_filename
from modules.demo_generator import generate_demo_movements, generate_demo_kits
